// Add a bot here to make it available in the selector. No UI code changes are needed.
window.CHATBOT_CONFIG = [
  {
    id: "cyno",
    name: "Cyno Software",
    adapter: "cyno-software",
    apiUrl: "http://127.0.0.1:3000/api/chat",
    staffApiUrl: "http://127.0.0.1:3000/api/chat-test/staff-message",
    enabled: true,
    channels: {
      website: {
        requestChannel: "chat-test",
        icebreakers: [
          { label: "Tư vấn Website", message: "Tôi muốn tư vấn Website", payload: "icebreaker:website" },
          { label: "Thiết kế lại Website", message: "Tôi muốn thiết kế lại Website", payload: "icebreaker:website_redesign" },
          { label: "SEO Website", message: "Tôi muốn tư vấn SEO Website", payload: "icebreaker:seo" },
          { label: "Phần mềm ERP", message: "Tôi muốn tư vấn phần mềm ERP", payload: "icebreaker:erp" },
          { label: "Phần mềm CRM", message: "Tôi muốn tư vấn phần mềm CRM", payload: "icebreaker:crm" },
          { label: "Phần mềm theo yêu cầu", message: "Tôi muốn tư vấn phần mềm theo yêu cầu", payload: "icebreaker:custom_software" },
          { label: "Tối ưu chuyển đổi", message: "Tôi muốn tối ưu chuyển đổi", payload: "icebreaker:conversion_optimization" },
          { label: "Bảo trì Website", message: "Tôi muốn tư vấn bảo trì Website", payload: "icebreaker:maintenance" },
        ],
      },
      messenger: {
        requestChannel: "messenger",
        quickReplyPayloadField: "quickReplyPayload",
        quickReplyPayloadValueField: "id",
        icebreakers: [
          { label: "Tư vấn Website", message: "Tôi muốn tư vấn Website", payload: "icebreaker:website" },
          { label: "Thiết kế lại Website", message: "Tôi muốn thiết kế lại Website", payload: "icebreaker:website_redesign" },
          { label: "SEO Website", message: "Tôi muốn tư vấn SEO Website", payload: "icebreaker:seo" },
          { label: "Phần mềm ERP", message: "Tôi muốn tư vấn phần mềm ERP", payload: "icebreaker:erp" },
          { label: "Phần mềm CRM", message: "Tôi muốn tư vấn phần mềm CRM", payload: "icebreaker:crm" },
          { label: "Phần mềm theo yêu cầu", message: "Tôi muốn tư vấn phần mềm theo yêu cầu", payload: "icebreaker:custom_software" },
          { label: "Tối ưu chuyển đổi", message: "Tôi muốn tối ưu chuyển đổi", payload: "icebreaker:conversion_optimization" },
          { label: "Bảo trì Website", message: "Tôi muốn tư vấn bảo trì Website", payload: "icebreaker:maintenance" },
        ],
      },
    },
    testMode: {
      enabled: true,
      label: "Telegram dry-run",
      requestBody: {
        testMode: "telegram-dry-run",
      },
      headers: {
        "X-Chatbot-Test-Mode": "telegram-dry-run",
      },
    },
  },
  {
    id: "cyno-v2",
    name: "Cyno Software V2",
    adapter: "cyno-software",
    apiUrl: "http://127.0.0.1:3000/api/chat",
    enabled: true,
    channels: {
      website: {
        requestChannel: "chat-test",
        icebreakers: [
          { label: "Tư vấn Website", message: "Tôi muốn tư vấn Website", payload: "icebreaker:website" },
          { label: "Thiết kế lại Website", message: "Tôi muốn thiết kế lại Website", payload: "icebreaker:website_redesign" },
          { label: "SEO Website", message: "Tôi muốn tư vấn SEO Website", payload: "icebreaker:seo" },
          { label: "Tối ưu chuyển đổi", message: "Tôi muốn tối ưu chuyển đổi", payload: "icebreaker:conversion_optimization" },
          { label: "Bảo trì Website", message: "Tôi muốn tư vấn bảo trì Website", payload: "icebreaker:maintenance" },
        ],
      },
      messenger: {
        requestChannel: "messenger",
        quickReplyPayloadField: "quickReplyPayload",
        quickReplyPayloadValueField: "id",
        icebreakers: [
          { label: "Tư vấn Website", message: "Tôi muốn tư vấn Website", payload: "icebreaker:website" },
          { label: "Thiết kế lại Website", message: "Tôi muốn thiết kế lại Website", payload: "icebreaker:website_redesign" },
          { label: "SEO Website", message: "Tôi muốn tư vấn SEO Website", payload: "icebreaker:seo" },
          { label: "Tối ưu chuyển đổi", message: "Tôi muốn tối ưu chuyển đổi", payload: "icebreaker:conversion_optimization" },
          { label: "Bảo trì Website", message: "Tôi muốn tư vấn bảo trì Website", payload: "icebreaker:maintenance" },
        ],
      },
    },
  },
  {
    id: "demo",
    name: "Demo Chatbot",
    apiUrl: "",
    enabled: true,
    channels: {
      website: {
        requestChannel: "chat-test",
      },
      messenger: {
        requestChannel: "messenger",
        quickReplyPayloadField: "quickReplyPayload",
        quickReplyPayloadValueField: "id",
      },
    },
    testMode: {
      enabled: true,
      label: "Telegram dry-run",
      requestBody: {
        testMode: "telegram-dry-run",
      },
      headers: {
        "X-Chatbot-Test-Mode": "telegram-dry-run",
      },
    },
  },
];

// Add regression scenarios here. A scenario with botId omitted applies to the selected bot.
window.CHATBOT_SCENARIOS = [
  {
    id: "cyno-greeting-smoke",
    botId: "cyno",
    name: "Cyno greeting smoke",
    messages: ["Xin chào"],
    assertions: {
      intent: "GREETING",
    },
  },
  {
    id: "cyno-v2-vague-website-need",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Nhu cầu website còn chung chung",
    messages: ["Mình đang muốn làm website cho công việc kinh doanh, chưa rõ nên bắt đầu từ đâu."],
    observableExpectations: ["Phản hồi tập trung vào nhu cầu website và hỏi làm rõ phù hợp hoặc đưa ra lựa chọn dễ trả lời."],
    behaviorExpectations: { consultationRelevance: true, singlePrimaryRequest: true, contextualContactRequest: true },
  },
  {
    id: "cyno-v2-clear-business-website",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Website doanh nghiệp với nhu cầu rõ",
    messages: ["Công ty logistics của mình cần website giới thiệu dịch vụ, hồ sơ năng lực và form nhận yêu cầu báo giá."],
    observableExpectations: ["Nhận diện nhu cầu website doanh nghiệp và phản hồi theo các mục đích đã nêu."],
    behaviorExpectations: { consultationRelevance: true, singlePrimaryRequest: true, contextualContactRequest: true },
  },
  {
    id: "cyno-v2-custom-website-function",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Website theo yêu cầu và chức năng cụ thể",
    messages: ["Mình muốn đặt làm website theo yêu cầu cho trung tâm ngoại ngữ.", "Cần học viên đăng ký lịch kiểm tra đầu vào và chọn cơ sở."],
    observableExpectations: ["Duy trì ngữ cảnh website theo yêu cầu và làm rõ chức năng đăng ký lịch/chọn cơ sở."],
    behaviorExpectations: { preserveContext: true, consultationRelevance: true, singlePrimaryRequest: true, boundedScopeAndFeasibility: true },
  },
  {
    id: "cyno-v2-website-redesign",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Thiết kế lại website",
    messages: ["Bên mình đã có website giới thiệu phòng khám nhưng giao diện cũ, muốn thiết kế lại cho dễ xem trên điện thoại."],
    observableExpectations: ["Tư vấn theo nhu cầu redesign website hiện có và mục tiêu mobile đã nêu."],
    behaviorExpectations: { consultationRelevance: true, singlePrimaryRequest: true, groundedWebsiteClaims: true, contextualContactRequest: true },
  },
  {
    id: "cyno-v2-website-speed-url",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Website chậm và cung cấp URL",
    messages: ["Website bán đồ thủ công của mình tải khá chậm, muốn tìm hiểu hướng cải thiện.", "Đây là địa chỉ website: https://example.com"],
    observableExpectations: ["Không nói đã truy cập, kiểm tra hoặc xác định nguyên nhân từ URL; có thể hỏi thông tin hoặc đề xuất bước kiểm tra phù hợp."],
    behaviorExpectations: { preserveContext: true, consultationRelevance: true, singlePrimaryRequest: true, groundedWebsiteClaims: true },
  },
  {
    id: "cyno-v2-seo-business-goal-area",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · SEO cho website hiện có",
    messages: ["Mình có website cho dịch vụ sửa điều hòa.", "Mục tiêu là nhận thêm khách tìm dịch vụ vệ sinh máy lạnh tại Đà Nẵng."],
    observableExpectations: ["Giữ nhu cầu SEO, website hiện có, mục tiêu kinh doanh và khu vực Đà Nẵng trong tư vấn."],
    behaviorExpectations: { preserveContext: true, consultationRelevance: true, singlePrimaryRequest: true, groundedWebsiteClaims: true, contextualContactRequest: true },
  },
  {
    id: "cyno-v2-correct-seo-to-redesign",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Sửa nhu cầu từ SEO sang redesign",
    messages: ["Mình muốn tìm hiểu SEO cho website công ty nội thất.", "Mình nói chưa đúng: hiện tại ưu tiên thiết kế lại website, chưa cần tư vấn SEO."],
    observableExpectations: ["Cập nhật nhu cầu hiện tại sang thiết kế lại website và không tiếp tục tư vấn SEO như nhu cầu chính."],
    behaviorExpectations: { preserveContext: true, consultationRelevance: true, singlePrimaryRequest: true, respectNeedCorrections: true },
  },
  {
    id: "cyno-v2-correct-website-subtype",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Sửa phân loại nhu cầu website mới",
    messages: ["Mình cần website mới cho thương hiệu mỹ phẩm, muốn khách xem sản phẩm và đặt mua.", "Mình xin sửa lại: chỉ cần website giới thiệu thương hiệu và danh mục sản phẩm, chưa bán hàng trực tuyến."],
    observableExpectations: ["Tôn trọng điều chỉnh phạm vi từ website bán hàng sang website giới thiệu và danh mục sản phẩm."],
    behaviorExpectations: { preserveContext: true, consultationRelevance: true, singlePrimaryRequest: true, respectNeedCorrections: true, boundedScopeAndFeasibility: true },
  },
  {
    id: "cyno-v2-multiple-services",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Nhu cầu nhiều dịch vụ hợp lệ",
    messages: ["Công ty du lịch của mình cần làm website mới và muốn được tư vấn SEO cho website sau khi ra mắt."],
    observableExpectations: ["Ghi nhận cả nhu cầu website mới và SEO, có thể làm rõ thứ tự ưu tiên mà không loại bỏ một nhu cầu hợp lệ."],
    behaviorExpectations: { consultationRelevance: true, singlePrimaryRequest: true, contextualContactRequest: true, boundedScopeAndFeasibility: true },
  },
  {
    id: "cyno-v2-website-software-order-integration",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Website kết nối phần mềm đơn hàng",
    messages: ["Mình đang lên kế hoạch làm website đặt hàng cho chuỗi cửa hàng thực phẩm.", "Bên mình muốn tìm hiểu việc đưa đơn hàng từ website vào phần mềm quản lý hiện có."],
    observableExpectations: ["Làm rõ phần mềm và luồng đơn hàng cần trao đổi; không tự thêm đồng bộ tồn kho, khách hàng, thanh toán hoặc hứa chắc tính khả thi."],
    behaviorExpectations: { preserveContext: true, consultationRelevance: true, singlePrimaryRequest: true, boundedScopeAndFeasibility: true },
  },
  {
    id: "cyno-v2-continue-after-contact-ignored",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Tiếp tục tư vấn khi chưa cung cấp liên hệ",
    messages: ["Mình muốn thiết kế lại website cho công ty tư vấn thuế.", "Mình muốn trang dịch vụ và hồ sơ đội ngũ dễ xem hơn."],
    observableExpectations: ["Tiếp tục trao đổi về nội dung trang dịch vụ/đội ngũ nếu khách chưa trả lời yêu cầu liên hệ; không lặp lại yêu cầu liên hệ máy móc."],
    behaviorExpectations: { preserveContext: true, noUnnecessaryRepetition: true, consultationRelevance: true, singlePrimaryRequest: true, contextualContactRequest: true },
  },
  {
    id: "cyno-v2-ambiguous-business-software",
    botId: "cyno-v2",
    channelMode: "messenger",
    name: "V2 · Nhu cầu phần mềm doanh nghiệp chưa rõ",
    messages: ["Công ty mình muốn có phần mềm quản lý cho hoạt động nội bộ, hiện mình chưa rõ nên chọn loại nào."],
    observableExpectations: ["Hỏi làm rõ nghiệp vụ hoặc nhóm người dùng phù hợp; không tự gán ERP/CRM cụ thể, khẳng định tính năng hay hứa khả thi khi chưa đủ thông tin."],
    behaviorExpectations: { consultationRelevance: true, singlePrimaryRequest: true, contextualContactRequest: true, boundedScopeAndFeasibility: true },
  },
];
